export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USER_TODOS = 'FETCH_USER_TODOS';
export const FETCH_USER_TODOS_SUCCESS = 'FETCH_USER_TODOS_SUCCESS';
export const FETCH_USER_TODOS_ERROR = 'FETCH_USER_TODOS_ERROR';

export const FETCH_All_BLOGS = 'FETCH_All_BLOGS';
export const FETCH_All_BLOGS_SUCCESS = 'FETCH_All_BLOGS_SUCCESS';
export const FETCH_All_BLOGS_ERROR = 'FETCH_All_BLOGS_ERROR';
